# Generated by Django 3.2.4 on 2021-08-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обпубликовано')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default='', max_length=100, verbose_name='Длительность урока'),
        ),
        migrations.AddField(
            model_name='post',
            name='fee',
            field=models.CharField(default='', max_length=100, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='post',
            name='seat',
            field=models.CharField(default='', max_length=100, verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='post',
            name='teacher',
            field=models.CharField(default='', max_length=100, verbose_name='Преподаватель'),
        ),
    ]
